### PR TITLE
Fix validateTypes failing when passing non-decimal floats

### PR DESCRIPTION
**Pull request by tmalahie**
When I pass a float value that is actually an integer (Like 1.0), the type checker fails even though it's technically valid.
This PR fixes the issue.

### CODE REVIEW

**Comment by zoedberg** [comment]
With this change a float number like 1.4 would be accepted as a integer. If you're sure the float number is actually representing an integer you should cast it to an integer before calling the rgb-lib method (e.g. by checking if `(number % 1 === 0)` you can be sure the number is actually an integer before casting it).

**Comment by tmalahie** [comment]
> With this change a float number like 1.4 would be accepted as a integer. If you're sure the float number is actually representing an integer you should cast it to an integer before calling the rgb-lib method (e.g. by checking if `(number % 1 === 0)` you can be sure the number is actually an integer before casting it).

I'm sorry but can you clarify that? Normally my changes do exactly the opposite, if a method expects a float like 1.4 I changed it so that it accepts 1.0 as well.
Methods that expect an integer will still fail if you pass a float (just tested again to be sure and I indeed get an error)

Did I misunderstand something? 🤔

**Comment by zoedberg** [comment]
Oops, I was expecting `Number.isInteger(obj)` to return false for 1.0 (I'm used to Rust, sorry). 
I'm still not sure this change is safe though, if `trueTypeOf` would become more precise then `isTypeSubset` would become incorrect. Maybe in `trueTypeOf` we can check if the number in string form contains a point and if so consider that number a float? I would prefer for the nodeJS library to stay as much similar to the Rust version as possible.

**Comment by tmalahie** [comment]
> Oops, I was expecting `Number.isInteger(obj)` to return false for 1.0 (I'm used to Rust, sorry). I'm still not sure this change is safe though, if `trueTypeOf` would become more precise then `isTypeSubset` would become incorrect. Maybe in `trueTypeOf` we can check if the number in string form contains a point and if so consider that number a float? I would prefer for the nodeJS library to stay as much similar to the Rust version as possible.

Ahah no problem!
About your last suggestion I don't think we can unfortunately... Javascript doesn't really have the concept of integers, all numbers are stored as floats, so there's no way to differentiate between an integer that is supposed to be an integer, and an integer that is a float with no decimal part.
Even when converting to string you don't get back the info
```
const x = 1.0;
console.log(x.toString()); // Displays "1";
```

**Comment by tmalahie** [comment]
One option is to expect a `bigint` when you need to pass an integer, some crypto libraries do that (like `ethers` for example). One advantage of `bigint` over primitive numbers is that you don't risk to have rounding errors with big numbers. Which is something we might want to ensure especially when dealing with currency 🙂
Ex:
```
console.log(9999999999999999); // Shows 10000000000000000 because of float rounding error
console.log(99999999999999999n) // Shows 99999999999999999n
```

**Comment by zoedberg** [comment]
Good idea! I would use `big.js` (https://github.com/MikeMcl/big.js/) though, since it supports also float numbers. But to avoid rounding errors the bindings should get strings (e.g. `*c_char`) instead of numbers (e.g. `c_float` or `c_uchar`) and then, inside rgb-lib (`bindings/c-ffi/src/utils.rs`), we should parse the strings into numbers. It should be relatively easy but it requires changing several binding APIs. Would you be willing to make the required changes?

**Comment by zoedberg** [comment]
@tmalahie we released a new version that gets numbers as strings and fixes the issue you described here. By accepting only numbers represented in string form and using big.js to check the number size we managed to make the library more similar to its Rust version and in this way `1.0` will be considered a float number and `1` an integer one.

**Pull request closed without merging**
